logo: # add logo name
title: Mountaineering around the world 
description: > # this means to ignore newlines until "baseurl:"
  Mountaineering blog
permalink: ':title/'
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Banner settings
video: mountains.mp4 # add banner video. Add your video file to the folder video
banner-title: "" # add banner title
# add banner description
banner-desc: “Any road followed precisely to its end leads precisely nowhere.<br/>Climb the mountain just a little bit to test that it's a mountain.<br/>From the top of the mountain, you cannot see the mountain.” — Franck Herbert 

# Author settings
author-pic: face.jpg # your photo
author-name: Arnaud TANGUY # your name
about-author: French Mountaineer, Robotics Engineer # about author

# Social link
# google_url:    # add url link
# twitter_url:   # add url link
instagram_url: https://www.instagram.com/arntanguy # add url link
# pinterest_url: # add url link
# dribbble_url:  # add url link
# facebook_url:  # add url link

# Disqus
discus_identifier: arntanguy # add your discus identifier.  Not your username.  To get this, register your forum here with a unique ID: https://disqus.com/admin/create/

# Contact form (encrypted email https://jumk.de/nospam/stopspam.html)
formspree: meqeboja

# Newsletter
# mailchimp: # add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Tracker
analytics:

# Paginate
paginate: 12
paginate_path: /page:num/

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-srcset

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
